import { CardDefinition } from "../CardDefinition";
import { tightBondEffect } from "../../effects/tightBond";
import { medicEffect } from "../../effects/medic";
import { moraleBoostEffect } from "../../effects/moraleBoost";
import { spyEffect } from "../../effects/spy";
import { fogEffect } from "../../effects/fogEffect";  
import { frostEffect } from "../../effects/frostEffect";
import { rainEffect } from "../../effects/rainEffect";

export const northernRealmsCards: CardDefinition[] = [
  {
    id: "balista_1",
    name: "Balista",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Ballista 1.png",
    handImage: "/assets/cards/hand/Ballista 1.png",
    bondGroup: "balista",
    ongoing: tightBondEffect
  },
  {
    id: "balista_2",
    name: "Balista",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Ballista 2.png",
    handImage: "/assets/cards/hand/Ballista 2.png",
    bondGroup: "balista",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_1",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue Stripes Commando 1.png",
    handImage: "/assets/cards/hand/Blue Stripes Commando 1.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_2",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue Stripes Commando 2.png",
    handImage: "/assets/cards/hand/Blue Stripes Commando 2.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_3",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue Stripes Commando 3.png",
    handImage: "/assets/cards/hand/Blue Stripes Commando 3.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_4",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue Stripes Commando 4.png",
    handImage: "/assets/cards/hand/Blue Stripes Commando 4.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_5",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue Stripes Commando 5.png",
    handImage: "/assets/cards/hand/Blue Stripes Commando 5.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "catapult_1",
    name: "Catapult",
    basePower: 8,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Catapult 1.png",
    handImage: "/assets/cards/hand/Catapult 1.png",
    bondGroup: "catapult",
    ongoing: tightBondEffect
  },
  {
    id: "catapult_2",
    name: "Catapult",
    basePower: 8,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Catapult 2.png",
    handImage: "/assets/cards/hand/Catapult 2.png",
    bondGroup: "catapult",
    ongoing: tightBondEffect
  },
  {
    id: "crinfrid_reavers_dragon_hunter_1",
    name: "Crinfrid Reavers Dragon Hunter",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Crinfrid Reavers Dragon Hunter 1.png",
    handImage: "/assets/cards/hand/Crinfrid Reavers Dragon Hunter 1.png",
    bondGroup: "crinfrid_reavers_dragon_hunter",
    ongoing: tightBondEffect
  },
  {
    id: "crinfrid_reavers_dragon_hunter_2",
    name: "Crinfrid Reavers Dragon Hunter",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Crinfrid Reavers Dragon Hunter 2.png",
    handImage: "/assets/cards/hand/Crinfrid Reavers Dragon Hunter 2.png",
    bondGroup: "crinfrid_reavers_dragon_hunter",
    ongoing: tightBondEffect
  },
  {
    id: "crinfrid_reavers_dragon_hunter_3",
    name: "Crinfrid Reavers Dragon Hunter",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Crinfrid Reavers Dragon Hunter 3.png",
    handImage: "/assets/cards/hand/Crinfrid Reavers Dragon Hunter 3.png",
    bondGroup: "crinfrid_reavers_dragon_hunter",
    ongoing: tightBondEffect
  },
  {
    id: "dethmold",
    name: "Dethmold",
    basePower: 6,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Dethmold.png",
    handImage: "/assets/cards/hand/Dethmold.png"
  },
  {
    id: "dun_banner_medic",
    name: "Dun Banner Medic",
    basePower: 5,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Dun Banner Medic.png",
    handImage: "/assets/cards/hand/Dun Banner Medic.png",
    onPlay: medicEffect
  },
  {
    id: "esterad_thyssen",
    name: "Esterad Thyssen",
    basePower: 10,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Esterad Thyssen.png",
    handImage: "/assets/cards/hand/Esterad Thyssen.png",
    isHero: true
  },
  {
    id: "foltest_king_of_temeria",
    name: "Foltest, King of Temeria",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest King of Temeria.png",
    handImage: "/assets/cards/hand/Foltest King of Temeria.png",
    isLeader: true,
    leaderAbility: (ctx) => { }
  },
  {
    id: "foltest_lord_commander_of_the_north",
    name: "Foltest, Lord Commander of the North",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest Lord Commander of the North.png",
    handImage: "/assets/cards/hand/Foltest Lord Commander of the North.png",
    isLeader: true,
    leaderAbility: (ctx) => { }
  },
  {
    id: "foltest_son_of_medell",
    name: "Foltest, Son of Medell",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest Son of Medell.png",
    handImage: "/assets/cards/hand/Foltest Son of Medell.png",
    isLeader: true,
    leaderAbility: (ctx) => { }
  },
  {
    id: "foltest_the_siegemaster",
    name: "Foltest, The Siegemaster",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest The Siegemaster.png",
    handImage: "/assets/cards/hand/Foltest The Siegemaster.png",
    isLeader: true,
    leaderAbility: (ctx) => { }
  },
  {
    id: "foltest_the_steel-forged",
    name: "Foltest, The Steel-Forged",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest The Steel-forged.png",
    handImage: "/assets/cards/hand/Foltest The Steel-forged.png",
    isLeader: true,
    leaderAbility: (ctx) => { }
  },
  {
    id: "john_natalis",
    name: "John Natalis",
    basePower: 10,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/John Natalis.png",
    handImage: "/assets/cards/hand/John Natalis.png",
    isHero: true
  },
  {
    id: "keadweni_siege_expert_1",
    name: "Keadweni Siege Expert",
    basePower: 1,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Kaedweni Siege Expert 1.png",
    handImage: "/assets/cards/hand/Kaedweni Siege Expert 1.png",
    ongoing: moraleBoostEffect
  },
  {
    id: "keadweni_siege_expert_2",
    name: "Keadweni Siege Expert",
    basePower: 1,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Kaedweni Siege Expert 2.png",
    handImage: "/assets/cards/hand/Kaedweni Siege Expert 2.png",
    ongoing: moraleBoostEffect
  },
  {
    id: "keadweni_siege_expert_3",
    name: "Keadweni Siege Expert",
    basePower: 1,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Kaedweni Siege Expert 3.png",
    handImage: "/assets/cards/hand/Kaedweni Siege Expert 3.png",
    ongoing: moraleBoostEffect
  },
  {
    id: "keira_metz",
    name: "Keira Metz",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Keira Metz.png",
    handImage: "/assets/cards/hand/Keira Metz.png",
  },
  {
    id: "philippa_eilhart",
    name: "Philippa Eilhart",
    basePower: 10,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Philippa Eilhart.png",
    handImage: "/assets/cards/hand/Philippa Eilhart.png",
    isHero: true
  },
  {
    id: "poor_fucking_infantry_1",
    name: "Poor Fucking Infantry",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Poor Fucking Infantry 1.png",
    handImage: "/assets/cards/hand/Poor Fucking Infantry 1.png",
    bondGroup: "poor_fucking_infantry",
    ongoing: tightBondEffect
  },
  {
    id: "poor_fucking_infantry_2",
    name: "Poor Fucking Infantry",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Poor Fucking Infantry 2.png",
    handImage: "/assets/cards/hand/Poor Fucking Infantry 2.png",
    bondGroup: "poor_fucking_infantry",
    ongoing: tightBondEffect
  },
  {
    id: "poor_fucking_infantry_3",
    name: "Poor Fucking Infantry",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Poor Fucking Infantry 3.png",
    handImage: "/assets/cards/hand/Poor Fucking Infantry 3.png",
    bondGroup: "poor_fucking_infantry",
    ongoing: tightBondEffect
  },
  {
    id: "prince_stennis",
    name: "Prince Stennis",
    basePower: 5,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Prince Stennis.png",
    handImage: "/assets/cards/hand/Prince Stennis.png",
    onPlay: spyEffect
  },
  {
    id: "redanian_foot_soldier_1",
    name: "Redanian Foot Soldier",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Redanian Foot Soldier 1.png",
    handImage: "/assets/cards/hand/Redanian Foot Soldier 1.png",
  },
  {
    id: "redanian_foot_soldier_2",
    name: "Redanian Foot Soldier",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Redanian Foot Soldier 2.png",
    handImage: "/assets/cards/hand/Redanian Foot Soldier 2.png",
  },
  {
    id: "sabrina_glevissig",
    name: "Sabrina Glevissig",
    basePower: 4,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Sabrina Glevissig.png",
    handImage: "/assets/cards/hand/Sabrina Glevissig.png",
  },
  {
    id: "shelden_skaggs",
    name: "Shelden Skaggs",
    basePower: 4,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Sheldon Skaggs.png",
    handImage: "/assets/cards/hand/Shelden Skaggs.png",
  },
  {
    id: "siege_tower_1",
    name: "Siege Tower",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Siege Tower 1.png",
    handImage: "/assets/cards/hand/Siege Tower 1.png",
  },
  {
    id: "siege_tower_2",
    name: "Siege Tower",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Siege Tower 2.png",
    handImage: "/assets/cards/hand/Siege Tower 2.png",
  },
  {
    id: "siegfried_of_denesle",
    name: "Siegfried of Denesle",
    basePower: 5,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Siegfried of Denesle.png",
    handImage: "/assets/cards/hand/Siegfried of Denesle.png",
  },
  {
    id: "sigismund_dijkstra",
    name: "Sigismund Dijkstra",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Sigismund Dijkstra.png",
    handImage: "/assets/cards/hand/Sigismund Dijkstra.png",
    onPlay: spyEffect
  },
  {
    id: "sile_de_bruyne",
    name: "Sile de Bruyne",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Sile de Tansarville.png",
    handImage: "/assets/cards/hand/Sile de Tansarville.png",
  },
  {
    id: "thaler",
    name: "Thaler",
    basePower: 1,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Thaler.png",
    handImage: "/assets/cards/hand/Thaler.png",
    onPlay: spyEffect
  },
  {
    id: "trebuchet_1",
    name: "Trebuchet",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Trebuchet  1.png",
    handImage: "/assets/cards/hand/Trebuchet  1.png",
    bondGroup: "trebuchet",
    ongoing: tightBondEffect
  },
  {
    id: "trebuchet_2",
    name: "Trebuchet",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Trebuchet  2.png",
    handImage: "/assets/cards/hand/Trebuchet  2.png",
    bondGroup: "trebuchet",
    ongoing: tightBondEffect
  },
  {
    id: "vernon_roche",
    name: "Vernon Roche",
    basePower: 10,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Vernon Roche.png",
    handImage: "/assets/cards/hand/Vernon Roche.png",
    isHero: true
  },
  {
    id: "ves",
    name: "Ves",
    basePower: 5,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Ves.png",
    handImage: "/assets/cards/hand/Ves.png",
  },
  {
    id: "yarpen_zigrin",
    name: "Yarpen Zigrin",
    basePower: 2,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Yarpen Zigrin.png",
    handImage: "/assets/cards/hand/Yarpen Zigrin.png",
  },
  {
  id: "fog",
  name: "Fog",
  basePower: 0,
  allowedRows: ["MELEE"],
  faction: "NEUTRAL",
  image: "/assets/cards/board/Fog.png",
  handImage: "/assets/cards/hand/Fog.png",
  auraEffect: fogEffect
},
{
  id: "frost",
  name: "Frost",
  basePower: 0,
  allowedRows: ["RANGED"],
  faction: "NEUTRAL",
  image: "/assets/cards/board/Frost.png",
  handImage: "/assets/cards/hand/Frost.png",
  auraEffect: frostEffect
},
{
  id: "rain",
  name: "Rain",
  basePower: 0,
  allowedRows: ["SIEGE"],
  faction: "NEUTRAL",
  image: "/assets/cards/board/Rain.png",
  handImage: "/assets/cards/hand/Rain.png",
  auraEffect: rainEffect
}
];  