import type { CardDefinition } from "../CardDefinition"
import type { CardPlayContext } from "../CardPlayContext"
import { tightBondEffect } from "../../effects/tightBond"
import { medicEffect } from "../../effects/medic"
import { moraleBoostEffect } from "../../effects/moraleBoost"
import { spyEffect } from "../../effects/spy"

// Add power badges to cards and fix Poor Fucking Infantry Tight Bond

export const northernRealmsCards: CardDefinition[] = [
  {
    id: "ballista_1",
    name: "Ballista",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Ballista_1.png",
    handImage: "/assets/cards/hand/Ballista_1.png"
  },
  {
    id: "ballista_2",
    name: "Ballista",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Ballista_2.png",
    handImage: "/assets/cards/hand/Ballista_2.png"
  },
  {
    id: "blue_stripes_commando_1",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue_Stripes_Commando_1.png",
    handImage: "/assets/cards/hand/Blue_Stripes_Commando_1.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_2",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue_Stripes_Commando_2.png",
    handImage: "/assets/cards/hand/Blue_Stripes_Commando_2.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_3",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue_Stripes_Commando_3.png",
    handImage: "/assets/cards/hand/Blue_Stripes_Commando_3.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_4",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue_Stripes_Commando_4.png",
    handImage: "/assets/cards/hand/Blue_Stripes_Commando_4.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "blue_stripes_commando_5",
    name: "Blue Stripes Commando",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Blue_Stripes_Commando_5.png",
    handImage: "/assets/cards/hand/Blue_Stripes_Commando_5.png",
    bondGroup: "blue_stripes_commando",
    ongoing: tightBondEffect
  },
  {
    id: "catapult_1",
    name: "Catapult",
    basePower: 8,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Catapult_1.png",
    handImage: "/assets/cards/hand/Catapult_1.png",
    bondGroup: "catapult",
    ongoing: tightBondEffect
  },
  {
    id: "catapult_2",
    name: "Catapult",
    basePower: 8,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Catapult_2.png",
    handImage: "/assets/cards/hand/Catapult_2.png",
    bondGroup: "catapult",
    ongoing: tightBondEffect
  },
  {
    id: "crinfrid_reavers_dragon_hunter_1",
    name: "Crinfrid Reavers Dragon Hunter",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Crinfrid_Reavers_Dragon_Hunter_1.png",
    handImage: "/assets/cards/hand/Crinfrid_Reavers_Dragon_Hunter_1.png",
    bondGroup: "crinfrid_reavers_dragon_hunter",
    ongoing: tightBondEffect
  },
  {
    id: "crinfrid_reavers_dragon_hunter_2",
    name: "Crinfrid Reavers Dragon Hunter",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Crinfrid_Reavers_Dragon_Hunter_2.png",
    handImage: "/assets/cards/hand/Crinfrid_Reavers_Dragon_Hunter_2.png",
    bondGroup: "crinfrid_reavers_dragon_hunter",
    ongoing: tightBondEffect
  },
  {
    id: "crinfrid_reavers_dragon_hunter_3",
    name: "Crinfrid Reavers Dragon Hunter",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Crinfrid_Reavers_Dragon_Hunter_3.png",
    handImage: "/assets/cards/hand/Crinfrid_Reavers_Dragon_Hunter_3.png",
    bondGroup: "crinfrid_reavers_dragon_hunter",
    ongoing: tightBondEffect
  },
  {
    id: "dethmold",
    name: "Dethmold",
    basePower: 6,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Dethmold.png",
    handImage: "/assets/cards/hand/Dethmold.png"
  },
  {
    id: "dun_banner_medic",
    name: "Dun Banner Medic",
    basePower: 5,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Dun_Banner_Medic.png",
    handImage: "/assets/cards/hand/Dun_Banner_Medic.png",
    onPlay: medicEffect
  },
  {
    id: "esterad_thyssen",
    name: "Esterad Thyssen",
    basePower: 10,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Esterad_Thyssen.png",
    handImage: "/assets/cards/hand/Esterad_Thyssen.png",
    isHero: true
  },
  {
    id: "foltest_king_of_temeria",
    name: "Foltest, King of Temeria",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest_King_Of_Temeria.png",
    handImage: "/assets/cards/hand/Foltest_King_Of_Temeria.png",
    isLeader: true,
    leaderAbility: (_ctx: CardPlayContext) => { }
  },
  {
    id: "foltest_lord_commander_of_the_north",
    name: "Foltest, Lord Commander of the North",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest_Lord_Commander_Of_The_North.png",
    handImage: "/assets/cards/hand/Foltest_Lord_Commander_Of_The_North.png",
    isLeader: true,
    leaderAbility: (_ctx: CardPlayContext) => { }
  },
  {
    id: "foltest_son_of_medell",
    name: "Foltest, Son of Medell",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest_Son_Of_Medell.png",
    handImage: "/assets/cards/hand/Foltest_Son_Of_Medell.png",
    isLeader: true,
    leaderAbility: (_ctx: CardPlayContext) => { }
  },
  {
    id: "foltest_the_siegemaster",
    name: "Foltest, The Siegemaster",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest_the_Siegemaster.png ",
    handImage: "/assets/cards/hand/Foltest_the_Siegemaster.png ",
    isLeader: true,
    leaderAbility: (_ctx: CardPlayContext) => { }
  },
  {
    id: "foltest_the_steel-forged",
    name: "Foltest, The Steel-Forged",
    basePower: 0,
    allowedRows: [],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Foltest_the_Steel-Forged.png ",
    handImage: "/assets/cards/hand/Foltest_the_Steel-Forged.png ",
    isLeader: true,
    leaderAbility: (_ctx: CardPlayContext) => { }
  },
  {
    id: "john_natalis",
    name: "John Natalis",
    basePower: 10,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/John_Natalis.png",
    handImage: "/assets/cards/hand/John_Natalis.png",
    isHero: true
  },
  {
    id: "kaedweni_siege_expert_1",
    name: "Kaedweni Siege Expert",
    basePower: 1,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Kaedweni_Siege_Expert_1.png",
    handImage: "/assets/cards/hand/Kaedweni_Siege_Expert_1.png",
    ongoing: moraleBoostEffect
  },
  {
    id: "kaedweni_siege_expert_2",
    name: "Kaedweni Siege Expert",
    basePower: 1,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Kaedweni_Siege_Expert_2.png",
    handImage: "/assets/cards/hand/Kaedweni_Siege_Expert_2.png",
    ongoing: moraleBoostEffect
  },
  {
    id: "kaedweni_siege_expert_3",
    name: "Kaedweni Siege Expert",
    basePower: 1,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Kaedweni_Siege_Expert_3.png",
    handImage: "/assets/cards/hand/Kaedweni_Siege_Expert_3.png",
    ongoing: moraleBoostEffect
  },
  {
    id: "keira_metz",
    name: "Keira Metz",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Keira_Metz.png",
    handImage: "/assets/cards/hand/Keira_Metz.png",
  },
  {
    id: "philippa_eilhart",
    name: "Philippa Eilhart",
    basePower: 10,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Philippa_Eilhart.png",
    handImage: "/assets/cards/hand/Philippa_Eilhart.png",
    isHero: true
  },
  {
    id: "poor_fucking_infantry_1",
    name: "Poor Fucking Infantry",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Poor_Fucking_Infantry_1.png",
    handImage: "/assets/cards/hand/Poor_Fucking_Infantry_1.png",
    ongoing: tightBondEffect
  },
  {
    id: "poor_fucking_infantry_2",
    name: "Poor Fucking Infantry",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Poor_Fucking_Infantry_2.png",
    handImage: "/assets/cards/hand/Poor_Fucking_Infantry_2.png",
    ongoing: tightBondEffect
  },
  {
    id: "poor_fucking_infantry_3",
    name: "Poor Fucking Infantry",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Poor_Fucking_Infantry_3.png",
    handImage: "/assets/cards/hand/Poor_Fucking_Infantry_3.png",
    ongoing: tightBondEffect
  },
  {
    id: "prince_stennis",
    name: "Prince Stennis",
    basePower: 5,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Prince_Stennis.png",
    handImage: "/assets/cards/hand/Prince_Stennis.png",
    onPlay: spyEffect
  },
  {
    id: "redanian_foot_soldier_1",
    name: "Redanian Foot Soldier",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Redanian_Foot_Soldier_1.png",
    handImage: "/assets/cards/hand/Redanian_Foot_Soldier_1.png",
  },
  {
    id: "redanian_foot_soldier_2",
    name: "Redanian Foot Soldier",
    basePower: 1,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Redanian_Foot_Soldier_2.png",
    handImage: "/assets/cards/hand/Redanian_Foot_Soldier_2.png",
  },
  {
    id: "sabrina_glevissig",
    name: "Sabrina Glevissig",
    basePower: 4,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Sabrina_Glevissig.png",
    handImage: "/assets/cards/hand/Sabrina_Glevissig.png",
  },
  {
    id: "shelden_skaggs",
    name: "Shelden Skaggs",
    basePower: 4,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Shelden_Skaggs.png",
    handImage: "/assets/cards/hand/Shelden_Skaggs.png",
  },
  {
    id: "siege_tower_1",
    name: "Siege Tower",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Siege_Tower_1.png",
    handImage: "/assets/cards/hand/Siege_Tower_1.png",
  },
  {
    id: "siege_tower_2",
    name: "Siege Tower",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Siege_Tower_2.png",
    handImage: "/assets/cards/hand/Siege_Tower_2.png",
  },
  {
    id: "siegfried_of_denesle",
    name: "Siegfried of Denesle",
    basePower: 5,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Siegfried_of_Denesle.png",
    handImage: "/assets/cards/hand/Siegfried_of_Denesle.png",
  },
  {
    id: "sigismund_dijkstra",
    name: "Sigismund Dijkstra",
    basePower: 4,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Sigismund_Dijkstra.png",
    handImage: "/assets/cards/hand/Sigismund_Dijkstra.png",
    onPlay: spyEffect
  },
  {
    id: "sile_de_bruyne",
    name: "Sile de Bruyne",
    basePower: 5,
    allowedRows: ["RANGED"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Sile_de_Tansarville.png",
    handImage: "/assets/cards/hand/Sile_de_Tansarville.png",
  },
  {
    id: "thaler",
    name: "Thaler",
    basePower: 1,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Thaler.png",
    handImage: "/assets/cards/hand/Thaler.png",
    onPlay: spyEffect
  },
  {
    id: "trebuchet_1",
    name: "Trebuchet",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Trebuchet_1.png",
    handImage: "/assets/cards/hand/Trebuchet_1.png",
  },
  {
    id: "trebuchet_2",
    name: "Trebuchet",
    basePower: 6,
    allowedRows: ["SIEGE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Trebuchet_2.png",
    handImage: "/assets/cards/hand/Trebuchet_2.png",
  },
  {
    id: "vernon_roche",
    name: "Vernon Roche",
    basePower: 10,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Vernon_Roche.png",
    handImage: "/assets/cards/hand/Vernon_Roche.png",
    isHero: true
  },
  {
    id: "ves",
    name: "Ves",
    basePower: 5,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Ves.png",
    handImage: "/assets/cards/hand/Ves.png",
  },
  {
    id: "yarpen_zigrin",
    name: "Yarpen Zigrin",
    basePower: 2,
    allowedRows: ["MELEE"],
    faction: "NORTHERN_REALMS",
    image: "/assets/cards/board/Yarpen_Zigrin.png",
    handImage: "/assets/cards/hand/Yarpen_Zigrin.png",
  },
];  